#!/usr/bin/env bash

declare -x PHP_MEMORY_LIMIT
[[ -z "${PHP_MEMORY_LIMIT}" ]] && PHP_MEMORY_LIMIT="1G"

declare -x PHP_POST_MAX_SIZE
[[ -z "${PHP_POST_MAX_SIZE}" ]] && PHP_POST_MAX_SIZE="2G"

declare -x PHP_UPLOAD_MAX_FILESIZE
[[ -z "${PHP_UPLOAD_MAX_FILESIZE}" ]] && PHP_UPLOAD_MAX_FILESIZE="2G"

declare -x PHP_MAX_EXECUTION_TIME
[[ -z "${PHP_MAX_EXECUTION_TIME}" ]] && PHP_MAX_EXECUTION_TIME="3600"

declare -x PHP_MAX_INPUT_TIME
[[ -z "${PHP_MAX_INPUT_TIME}" ]] && PHP_MAX_INPUT_TIME="3600"

declare -x PHP_DATE_TIMEZONE
[[ -z "${PHP_DATE_TIMEZONE}" ]] && PHP_DATE_TIMEZONE="UTC"

declare -x PHP_LOG_LEVEL
[[ -z "${PHP_LOG_LEVEL}" ]] && PHP_LOG_LEVEL="warning"

declare -x PHP_MAX_CHILDREN
[[ -z "${PHP_MAX_CHILDREN}" ]] && PHP_MAX_CHILDREN="75"

declare -x PHP_MAX_REQUESTS
[[ -z "${PHP_MAX_REQUESTS}" ]] && PHP_MAX_REQUESTS="500"

declare -x PHP_PROCESS_IDLE_TIMEOUT
[[ -z "${PHP_PROCESS_IDLE_TIMEOUT}" ]] && PHP_PROCESS_IDLE_TIMEOUT="10s"

declare -x PHP_FPM_CLEAR_ENV
[[ -z "${PHP_FPM_CLEAR_ENV}" ]] && PHP_FPM_CLEAR_ENV="no"

declare -x PHP_INI_EXPOSE
[[ -z "${PHP_INI_EXPOSE}" ]] && PHP_INI_EXPOSE="Off"

declare -x CONFIGURE_CUSTOM
[[ -z "${CONFIGURE_CUSTOM}" ]] && CONFIGURE_CUSTOM="false"

declare -x PHP_RUN_USER
[[ -z "${PHP_RUN_USER}" ]] && PHP_RUN_USER="nginx"

declare -x PHP_RUN_GROUP
[[ -z "${PHP_RUN_GROUP}" ]] && PHP_RUN_GROUP="nginx"

declare -x PHP_OPCACHE_ENABLED
[[ -z "${PHP_OPCACHE_ENABLED}" ]] && PHP_OPCACHE_ENABLED="1"
