#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

if [ -f ./configure-custom ]
then
  source ./configure-custom
fi

echo "> alpine version $(cat /etc/alpine-release)"
echo "> php opcache enabled"

echo "> starting php"
exec /usr/sbin/php-fpm7 --allow-to-run-as-root