#!/bin/bash
source /usr/bin/entrypoint

echo "> writing php config"
/usr/bin/templater -d -p php \
  -o /etc/php7/php.ini \
  /etc/templates/php.ini.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi

echo "> writing fpm config"
/usr/bin/templater -d -p php \
  -o /etc/php7/php-fpm.conf \
  /etc/templates/php-fpm.conf.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi
