#!/bin/bash
source /usr/bin/entrypoint

echo "> writing php config"
/usr/bin/gomplate \
    -o /etc/php7/php.ini \
    -f /etc/templates/php.ini.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi

echo "> writing fpm config"
/usr/bin/gomplate \
    -o /etc/php7/php-fpm.conf \
    -f /etc/templates/php-fpm.conf.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi

echo "> php version is: $(php -r 'echo phpversion();')"
